import type { Metadata } from "next";
import { Montserrat, Hind, Dancing_Script } from 'next/font/google'
import "./globals.scss";
import Link from 'next/link';


export const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const hind = Hind({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-hind",
});

export const dancing = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${montserrat.variable} ${dancing.variable} ${hind.variable} ` } lang="fr">
      <body>
        <header id="headermove">
            <nav>
                <ul >
                    <li className="p-7"><Link href={"/"}>HOME</Link></li>
                    <li className="p-7"><Link href={"/projets"}>PROJETS</Link></li>
                    <li className="p-7"><Link href={"/contact"}>CONTACT</Link></li>
                </ul>
            </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
